{
 "title": "Temp",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "cfrate", "label": "Flat Rate", "query": "1" },
   { "name": "ccom", "label": "Commission Price", "query": "0" },
   { "name": "ccomthresh", "label": "Commission Threshold", "query": "0" },
   { "name": "ccheck", "label": "Include 'No Shows'?", "query": "Yes, No" }
  ]
 },
 "panels": [
  {
   "title": "Total Classes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT count(meetings.id) as Sessions\r\nFROM dev.staff as staff JOIN dev.meetings as meetings \r\non staff.id=meetings.staff_id\r\nwhere staff.job=\"Coach\" AND meetings.created_at  and CONVERT(meetings.created_at, DATETIME) between CONVERT_TZ(from_unixtime($__unixEpochFrom()),'+00:00', '-05:00') and CONVERT_TZ(from_unixtime($__unixEpochTo()),'+00:00' , '-05:00')\r\n"
    }
   ]
  },
  {
   "title": "Total Active Coaches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT count(Distinct staff.id) as Sessions\r\nFROM dev.staff as staff JOIN dev.meetings as meetings \r\non staff.id=meetings.staff_id\r\nwhere staff.job=\"Coach\" AND meetings.created_at  and CONVERT(meetings.created_at, DATETIME) between CONVERT_TZ(from_unixtime($__unixEpochFrom()),'+00:00', '-05:00') and CONVERT_TZ(from_unixtime($__unixEpochTo()),'+00:00' , '-05:00')\r\n"
    }
   ]
  },
  {
   "title": "Total Coaches",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT count(staff.id)\r\nFROM dev.staff as staff\r\nwhere staff.job=\"Coach\""
    }
   ]
  },
  {
   "title": "Classes Scheduled per Coach",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT staff.id as CoachID, staff.name as Name, count(staff.id) as Sessions\r\nFROM dev.staff as staff JOIN dev.meetings as meetings \r\non staff.id=meetings.staff_id\r\nwhere staff.job=\"Coach\" AND meetings.created_at  and CONVERT(meetings.created_at, DATETIME) between CONVERT_TZ(from_unixtime($__unixEpochFrom()),'+00:00', '-05:00') and CONVERT_TZ(from_unixtime($__unixEpochTo()),'+00:00' , '-05:00')\r\ngroup by staff.id\r\n"
    }
   ]
  },
  {
   "title": "Classes Scheduled per Coach",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Percentage Filled per Class",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n    meetings.id as MeetingID,\r\n    staff.name as Coach,\r\n    services.name as Service,\r\n    loc.name as Location,\r\n    COUNT(DISTINCT rez.users_id) as Users,\r\n    meetings.capacity as Capacity,\r\n    (COUNT(DISTINCT rez.users_id) / meetings.capacity) * 100 as Percentage\r\nFROM\r\n    dev.meetings as meetings\r\nJOIN\r\n    dev.reservations as rez ON meetings.id = rez.meetings_id\r\nJOIN\r\n    dev.staff as staff ON meetings.staff_id = staff.id\r\nJOIN\r\n    dev.services as services ON meetings.services_id = services.id\r\nJOIN\r\n    dev.locations as loc ON meetings.locations_id = loc.id\r\nWHERE\r\n    rez.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\n    AND staff.job = \"Coach\"\r\nGROUP BY\r\n    meetings.id,\r\n    meetings.capacity,\r\n    staff.name,\r\n    services.name,\r\n    loc.name\r\n"
    }
   ]
  },
  {
   "title": "Percentage Filled per Class (Coaches)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n    meetings.id as MeetingID,\r\n    staff.name as Coach,\r\n    (COUNT(DISTINCT rez.users_id) / meetings.capacity) * 100 as Percentage\r\nFROM\r\n    dev.meetings as meetings\r\nJOIN\r\n    dev.reservations as rez ON meetings.id = rez.meetings_id\r\nJOIN\r\n    dev.staff as staff ON meetings.staff_id = staff.id\r\nWHERE\r\n    rez.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\n    AND staff.job = \"Coach\"\r\nGROUP BY\r\n    meetings.id,\r\n    staff.name"
    }
   ]
  },
  {
   "title": "Percentage Filled per Class (Services)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n    meetings.id as MeetingID,\r\n    services.name as Service,\r\n    (COUNT(DISTINCT rez.users_id) / meetings.capacity) * 100 as Percentage\r\nFROM\r\n    dev.meetings as meetings\r\nJOIN\r\n    dev.reservations as rez ON meetings.id = rez.meetings_id\r\nJOIN\r\n    dev.staff as staff ON meetings.staff_id = staff.id\r\nJOIN\r\n    dev.services as services ON meetings.services_id = services.id\r\nWHERE\r\n    rez.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\n    AND staff.job = \"Coach\"\r\nGROUP BY\r\n    meetings.id,\r\n    services.name\r\n"
    }
   ]
  },
  {
   "title": "Percentage Filled per Class (Locations)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n    meetings.id as MeetingID,\r\n    loc.name as Location,\r\n    (COUNT(DISTINCT rez.users_id) / meetings.capacity) * 100 as Percentage\r\nFROM\r\n    dev.meetings as meetings\r\nJOIN\r\n    dev.reservations as rez ON meetings.id = rez.meetings_id\r\nJOIN\r\n    dev.staff as staff ON meetings.staff_id = staff.id\r\nJOIN\r\n    dev.locations as loc ON meetings.locations_id = loc.id\r\nWHERE\r\n    rez.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\n    AND staff.job = \"Coach\"\r\nGROUP BY\r\n    meetings.id,\r\n    loc.name\r\n"
    }
   ]
  },
  {
   "title": "Payment per Coach Breakdown",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 14 }
   ]
  },
  {
   "title": "Payment per Coach",
   "type": "table",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 32 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT\r\n    loc.name as Location,\r\n    staff.name as Coach,\r\n    COUNT(DISTINCT meetings.id) as Classes,\r\n    COUNT(DISTINCT rez.users_id) as Attendance,\r\n    COUNT(DISTINCT rez.id) as Reservations,\r\n    CASE\r\n        WHEN \"$cfrate\" < 0 OR \"$ccom\" < 0 THEN 'ERR'\r\n        WHEN \"$cfrate\" IS NULL OR \"$ccom\" IS NULL THEN 0\r\n        WHEN \"$cfrate\" > 0 AND \"$ccom\" = 0 THEN \"$cfrate\" * COUNT(DISTINCT meetings.id)\r\n        WHEN \"$ccom\" IS NOT NULL THEN\r\n            CASE\r\n                WHEN \"$ccomthresh\" = 0 THEN \"$ccom\" * COUNT(DISTINCT rez.id)\r\n                WHEN (\"$ccomthresh\" > 0 AND COUNT(DISTINCT rez.id) = \"$ccomthresh\") THEN 0\r\n                WHEN (\"$ccomthresh\" > 0 AND COUNT(DISTINCT rez.id) > \"$ccomthresh\") THEN (COUNT(DISTINCT rez.id) - \"$ccomthresh\") * \"$ccom\"\r\n                WHEN (\"$ccomthresh\" > 0 AND COUNT(DISTINCT rez.id) < \"$ccomthresh\") THEN 0\r\n                ELSE\r\n                    'ERR'\r\n            END\r\n        ELSE NULL\r\n    END as Payment\r\nFROM\r\n    dev.meetings as meetings\r\nJOIN\r\n    dev.reservations as rez ON meetings.id = rez.meetings_id\r\nJOIN\r\n    dev.staff as staff ON meetings.staff_id = staff.id\r\nJOIN\r\n    dev.locations as loc ON meetings.locations_id = loc.id\r\nWHERE\r\n    rez.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\n    AND staff.job = \"Coach\"\r\n    AND (\r\n        \"$ccheck\" = \"Yes\"\r\n        OR (\"$ccheck\" = \"No\" AND rez.cancelled = 0)\r\n    )\r\nGROUP BY\r\n    meetings.staff_id,\r\n    loc.id\r\nLIMIT 10;\r\n"
    }
   ]
  }
 ]
}