{
 "title": "Active Memberships",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "Total Payment from Memberships",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Payment Over Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Payment based on Membership Status",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Membersahips Availed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Active Memberships over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 13 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Status of Users With Memberhsips",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Membersahips Availed over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 23 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Total Memberships",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT id, name, price, status\r\nFROM\r\n    dev.memberships"
    }
   ]
  },
  {
   "title": "Total Credits from Memberships",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Credits from Memberships over Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 34 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Credits Details based on Membership Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Credits Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Payment Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT memberships.name as Membership, uprofiles.first_name as Profile, users.name as User_Name, uprofiles.email as Email, memberships.status as Status, memberships.price as Original_Price, purchases.subtotal as Final_Price, memberships.created_at as Creation_Date, umemberships.expiration_date as Expiration_Date\r\nFROM\r\n    dev.memberships as memberships\r\nJOIN\r\n    dev.users_memberships as umemberships ON memberships.id = umemberships.memberships_id\r\nJOIN\r\n    dev.user_profiles as uprofiles ON umemberships.user_profiles_id = uprofiles.id\r\nJOIN\r\n    dev.users as users ON users.id = uprofiles.users_id\r\nJOIN\r\n    dev.purchases as purchases ON purchases.users_id = users.id\r\nWHERE\r\n    memberships.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')"
    }
   ]
  },
  {
   "title": "Membership Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT memberships.name as Membership, uprofiles.first_name as Profile, users.name as User_Name, uprofiles.email as Email, locations.name as Location, memberships.status as Status, memberships.price as Original_Price, pitems.item_price_final as Item_Price, pitems.item_credits as Item_Credits, credits.name as Credit_Name, purchases.subtotal as Final_Price, memberships.created_at as Creation_Date, umemberships.expiration_date as Expiration_Date\r\nFROM\r\n    dev.memberships as memberships\r\nJOIN\r\n    dev.users_memberships as umemberships ON memberships.id = umemberships.memberships_id\r\nJOIN\r\n    dev.user_profiles as uprofiles ON umemberships.user_profiles_id = uprofiles.id\r\nJOIN\r\n    dev.users as users ON users.id = uprofiles.users_id\r\nJOIN\r\n    dev.membership_credits as mcredits ON mcredits.memberships_id = memberships.id\r\nJOIN\r\n    dev.credits as credits ON credits.id = mcredits.credits_id\r\nJOIN\r\n    dev.purchase_items as pitems ON pitems.users_id = users.id\r\nJOIN\r\n    dev.purchases as purchases ON purchases.id = pitems.purchases_id\r\nJOIN\r\n    dev.locations as locations ON locations.id = pitems.locations_id\r\n\r\nWHERE\r\n    memberships.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')"
    }
   ]
  }
 ]
}