{
 "title": "Remaining Series",
 "time": { "from": "2021-04-09T23:45:31.923Z", "to": "2025-04-10T23:45:31.923Z" },
 "templating": {
  "list": [
   { "name": "brands", "label": "Brands", "query": "SELECT id FROM dev.brands\n" },
   {
    "name": "packagestatus",
    "label": "Package Status",
    "query": "active , inactive , canceled : NULL"
   },
   { "name": "limit", "label": "Record Limit", "query": "50,500,5000,50000,500000" }
  ]
 },
 "panels": [
  {
   "title": "Total Purchases",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Total Average Purchases Value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Total Starting Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Total Starting Value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Total Remaining Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Total Remaining Value",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Package Comparisons",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Starting Counts per Package",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Starting Value per Package",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Remaining Counts per Package",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Remaining Value per Package",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "Packages Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT \r\n    Package2,\r\n    COUNT(*) AS Total_Purchases,\r\n    AVG(Total_Price) AS Avg_Price,\r\n    SUM(Package_Credits) AS Total_Credits,\r\n    SUM(CASE WHEN Package_Used = 0 THEN Credits_Price ELSE 0 END) AS Unused_Credits_Price,\r\n    SUM(Credits_Price) AS Total_Credits_Price,\r\n    SUM(CASE WHEN Package_Used = 0 THEN Purchased_Credits ELSE 0 END) AS Unused_Credits\r\nFROM (\r\n    SELECT \r\n        uprofiles.first_name AS User,\r\n        uprofiles.email AS Email,\r\n        combos.name AS Package2,\r\n        ucredits.used AS Package_Used,\r\n        IF(DATE(ucredits.expiration_date) < CURDATE(), 'Expired', IF(ucredits.deleted_at IS NOT NULL, 'Canceled', 'Active')) AS Package_Status,\r\n        combos.credits AS Package_Credits,\r\n        combos.price AS Package_Price,\r\n        (pitems.item_price_final / (pitems.quantity * combos.credits)) AS Credits_Price,\r\n        pitems.quantity AS Quantity,\r\n        purchases.subtotal AS Total_Price,\r\n        pitems.item_credits AS Purchased_Credits,\r\n        locations.name AS Location,\r\n        ucredits.created_at AS Date,\r\n        ucredits.expiration_date AS Expiry\r\n    FROM\r\n        dev.credits AS credits\r\n    JOIN\r\n        dev.users_credits AS ucredits ON credits.id = ucredits.credits_id\r\n    JOIN\r\n        dev.combos AS combos ON combos.credits_id = credits.id\r\n    JOIN\r\n        dev.user_profiles AS uprofiles ON ucredits.user_profiles_id = uprofiles.id\r\n    JOIN\r\n        dev.purchase_items AS pitems ON pitems.credits_id = credits.id\r\n    JOIN\r\n        dev.purchases AS purchases ON purchases.id = pitems.purchases_id\r\n    JOIN\r\n        dev.locations AS locations ON locations.id = pitems.locations_id\r\n    WHERE\r\n        purchases.brands_id IN ($brands) AND\r\n        combos.status IN ($packagestatus) AND\r\n        ucredits.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                                AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\n    LIMIT $limit\r\n) AS subquery\r\nGROUP BY\r\n    Package2;\r\n"
    }
   ]
  },
  {
   "title": "User Packages Status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Packages Availed Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Ammount Recieved Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Package Status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT id, IF( deleted_at is not null, 'Canceled' , status) as status\r\nFROM combos;"
    }
   ]
  },
  {
   "title": "Earnings per Package",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Earnings per Location",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Packages Availed by Users",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 72 },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "All Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT uprofiles.first_name as User, uprofiles.email as Email, combos.name as Package2, ucredits.used as Package_Used, IF(DATE(ucredits.expiration_date) < CURDATE(), 'Expired', IF( ucredits.deleted_at is not null, 'Canceled' ,'Active')) as Package_Status, combos.credits as Package_Credits, combos.price as Package_Price, (pitems.item_price_final / (pitems.quantity * combos.credits)) as Credits_Price, pitems.quantity as Quantity, purchases.subtotal as Total_Price, pitems.item_credits as Purchased_Credits, locations.name as Location, ucredits.created_at as Date, ucredits.expiration_date as Expiry\r\nFROM\r\n    dev.credits as credits\r\nJOIN\r\n    dev.users_credits as ucredits ON credits.id = ucredits.credits_id\r\nJOIN\r\n    dev.combos as combos ON combos.credits_id = credits.id\r\nJOIN\r\n    dev.user_profiles as uprofiles ON ucredits.user_profiles_id = uprofiles.id\r\nJOIN\r\n    dev.purchase_items as pitems ON pitems.credits_id = credits.id\r\nJOIN\r\n    dev.purchases as purchases ON purchases.id = pitems.purchases_id\r\nJOIN\r\n    dev.locations as locations ON locations.id = pitems.locations_id\r\nWHERE\r\n    purchases.brands_id IN ($brands) AND\r\n    combos.status IN ($packagestatus) AND\r\n    ucredits.created_at BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\nLIMIT $limit"
    }
   ]
  }
 ]
}