{
 "title": "Attendence Summary",
 "time": { "from": "2015-05-07T08:25:28.000Z", "to": "2023-12-25T00:41:32.000Z" },
 "templating": {
  "list": [
   { "name": "brand_id", "label": "Brand", "query": "SELECT id FROM brands" },
   { "name": "cancel", "label": "Session Cancelled", "query": "Yes : 1 , No : 0" },
   { "name": "location", "label": "Location", "query": "SELECT name FROM dev.locations" }
  ]
 },
 "panels": [
  {
   "title": "Total Reservations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT uprofiles.first_name as User, uprofiles.email as Email, locations.name as Location, reservations.meetings_id as Meeting_ID, staff.name as Staff, reservations.cancelled as Cancelled, reservations.meeting_start Meeting_Date\r\nFROM\r\n    dev.user_profiles as uprofiles\r\nJOIN\r\n    dev.reservations as reservations ON reservations.user_profiles_id = uprofiles.id\r\nJOIN\r\n    dev.staff as staff ON reservations.staff_id = staff.id\r\nJOIN\r\n    dev.locations as locations ON locations.id = reservations.locations_id\r\nWHERE\r\n    reservations.brands_id = $brand_id AND\r\n    reservations.meeting_start BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00');"
    }
   ]
  },
  {
   "title": "Reservations Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Reservations Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Cancelled Sessions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 5 }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT  \r\n    SUBSTRING(reservations.meeting_start, 1, 10) as Date,\r\n    COUNT(reservations.id) as Total,\r\n    SUM(CASE WHEN reservations.cancelled = 0 AND paytypes.name NOT LIKE \"%comp%\" THEN 1 ELSE 0 END) as Paid,\r\n    SUM(CASE WHEN reservations.cancelled = 0 AND paytypes.name LIKE \"%comp%\" THEN 1 ELSE 0 END) as Comped,\r\n    SUM(CASE WHEN reservations.cancelled = 0 AND reservations.attendance = 'first-time' THEN 1 ELSE 0 END) as \"First Time\",\r\n    SUM(CASE WHEN reservations.cancelled = 0 AND (reservations.attendance IS NULL OR reservations.attendance = 'not-attended' OR reservations.attendance = '') THEN 1 ELSE 0 END) as \"No Shows\",\r\n    SUM(CASE WHEN reservations.cancelled = 1 THEN 1 ELSE 0 END) as Cancelled,\r\n    COUNT(waitlist.reservations_id) as Waitlisted,\r\n    SUM(CASE WHEN reservations.cancelled = 0 AND reservations.attendance != 'first-time' THEN 1 ELSE 0 END) as \"Repeat\",\r\n    ROUND(COUNT(reservations.id) / COUNT(DISTINCT reservations.meetings_id)) as AVG,\r\n    COUNT(DISTINCT reservations.meetings_id) as \"Number Classes\",\r\n    LEAST((COUNT(reservations.id) / (COUNT(DISTINCT reservations.meetings_id) * 29)) * 100,100) as Capacity,\r\n    (SUM(CASE WHEN reservations.cancelled = 0 AND paytypes.name NOT LIKE \"%comp%\" THEN 1 ELSE 0 END) / COUNT(reservations.id)) * 100 as Paying,\r\n    SUM(CASE WHEN reservations.cancelled = 0 AND paytypes.name NOT LIKE \"%comp%\" THEN pitems.item_price_final ELSE 0 END) as Revenue\r\nFROM\r\n    reservations as reservations JOIN reservation_credits as rescredits ON reservations.id=rescredits.reservations_id\r\n    JOIN meetings as meetings ON reservations.meetings_id=meetings.id\r\n    JOIN users_credits as ucredits ON rescredits.users_credits_id=ucredits.id\r\n    JOIN purchases as purchases ON ucredits.purchases_id=purchases.id\r\n    JOIN purchase_items as pitems ON pitems.purchases_id = purchases.id\r\n    JOIN payment_types as paytypes ON purchases.payment_types_id=paytypes.id\r\n    LEFT OUTER JOIN dev.waitlist as waitlist ON reservations.id = waitlist.reservations_id\r\nWHERE\r\n    reservations.deleted_at IS NULL AND\r\n    pitems.buyed_type LIKE \"%Combos%\" AND\r\n    reservations.meeting_start BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                                AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00')\r\nGROUP BY\r\n    SUBSTRING(reservations.meeting_start, 1, 10);"
    }
   ]
  },
  {
   "title": "Attendance Status",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Reservations per Customer",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Reservations per Service",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Reservations per Coach",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Reservations per Coach",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 35 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "All Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "dev",
     "rawSql": "SELECT  uprofiles.first_name as User,\r\n        uprofiles.email as Email,\r\n        memberships.name as Membership,\r\n        CASE\r\n            WHEN reservations.attendance IS NULL THEN 'not-attended'\r\n            ELSE reservations.attendance\r\n        END AS Attendance,\r\n        locations.name as Location,\r\n        reservations.meetings_id as Meeting_ID,\r\n        staff.name as Staff,\r\n        services.name as Service,\r\n        reservations.cancelled as Cancelled,\r\n        reservations.meeting_start Meeting_Date\r\nFROM\r\n    dev.user_profiles as uprofiles\r\nJOIN\r\n    dev.users_memberships as umemberships ON umemberships.user_profiles_id = uprofiles.id\r\nJOIN\r\n    dev.memberships as memberships ON umemberships.memberships_id = memberships.id\r\nJOIN\r\n    dev.reservations as reservations ON reservations.user_profiles_id = uprofiles.users_id\r\nJOIN\r\n    dev.services as services ON reservations.services_id = services.id\r\nJOIN\r\n    dev.staff as staff ON reservations.staff_id = staff.id\r\nJOIN\r\n    dev.locations as locations ON locations.id = reservations.locations_id\r\nWHERE\r\n    reservations.brands_id = $brand_id AND\r\n    reservations.cancelled IN ($cancel) AND\r\n    locations.name IN ($location) AND\r\n    reservations.meeting_start BETWEEN CONVERT_TZ(FROM_UNIXTIME($__unixEpochFrom()), '+00:00', '-05:00')\r\n                      AND CONVERT_TZ(FROM_UNIXTIME($__unixEpochTo()), '+00:00', '-05:00');"
    }
   ]
  }
 ]
}